#!/bin/sh
echo this is a post-commit script
pwd

# build the war file
ant war

# upload the war file to aws tomcat server webapps directory
scp -i zbhuang0625.pem demo.war ec2-user@13.59.181.21:/usr/share/tomcat8/webapps
sleep 3

ant clean

# call the script you want
