#!/bin/sh
echo look at me I am the post-commit script
pwd

# build the war file
ant war

# upload the war file to aws tomcat server webapps directory
scp -i zbhuang0625.pem demo.war ec2-user@18.221.214.173:/usr/share/tomcat8/webapps
sleep 3

ant clean

# call the script you want
